### PR TITLE
[DDO-2759] Show user list for environment owner field

### PR DESCRIPTION
**Pull request by jack-r-warren**
Technically independent of https://github.com/broadinstitute/sherlock/pull/145 because the API didn't change.

Screenshot 2023-03-31 at 5 56 08 PM

### CODE REVIEW

**Comment by em-may** [comment]
Is "no" the default option for the "Name Prefixes Domain" option? Wouldn't we want that to always be yes? The way I understand that option is that it would allow you to choose between, e.g. `sam.<bee-name>.bee.envs-terra.bio` and `sam.bee.envs-terra.bio` (which I don't image we want to do). Am I missing something here?

**Comment by jack-r-warren** [comment]
> Is "no" the default option for the "Name Prefixes Domain" option? Wouldn't we want that to always be yes? The way I understand that option is that it would allow you to choose between, e.g. `sam.<bee-name>.bee.envs-terra.bio` and `sam.bee.envs-terra.bio` (which I don't image we want to do). Am I missing something here?

The screenshot is showing me editing dev. Dev does not have its name prefixing the domain.

**Comment by em-may** [comment]
I see. I didn't realize that there's a `*.dev.bee.envs-terra.bio` env. Is that new? Or am I just mistaking regular dev for bees?

**Comment by jack-r-warren** [comment]
> I see. I didn't realize that there's a `*.dev.bee.envs-terra.bio` env. Is that new? Or am I just mistaking regular dev for bees?

Environment names are globally unique. The "Now Editing dev" at the top of the screenshot shows that the page I'm linking to is normal dev. https://broad.io/beehive/environments/dev/edit

**Review by em-may — APPROVED** [review]

**Pull request merged**
